### ISSUE TITLE
Update helm chart to allow a secret to be specified

### ISSUE THREAD

**Issue by lknite** [vmware/load-balancer-and-ingress-services-for-kubernetes#1367]
### Is your feature request related to a problem? Please describe.

I'd like to pull avi credentials from a vault and then create a secret with those credentials.  This can be achieved using sealed-secrets.

The problem is, ako doesn't wait for the secret to appear and use it, instead it just creates its own secret overwriting the secret if it already exists.

### Describe the solution you'd like

1. Allow a secretName: to be specified rather than require the secret to be added to the values.yaml in order to be used.

```
avicredentials:
  existingSecretName: <secretName>
  username: ""
  password: ""
  authtoken: ""
  certificateAuthorityData:
```

If 'existingSecretName' is empty then use the passed in values, otherwise expect a secret with the name 'secretName' to exist with the needed values.

2. Also allow an initContainer to be specified so that I can add an initContainer which will wait for the secret to appear.  This can be added by adding the vmware 'common' library as a dependency to this helm chart.  Liko so:
```
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
```

### Describe alternatives you've considered

I tried creating the 'avi-secret' secret prior to deploying ako but it was simply overwritten.
