### ISSUE TITLE
AKO cleanup times out when there is no workload

### ISSUE THREAD

**Issue by maplain** [vmware/load-balancer-and-ingress-services-for-kubernetes#242]
When cluster has no LB SVC workload, setting `deleteConfig` to `True` will leave the StatefulSet status stuck in:
```
status:
  collisionCount: 0
  conditions:
  - lastTransitionTime: "2021-01-12T22:16:45Z"
    message: Started deleting objects
    reason: Started
    status: "True"
    type: ako.vmware.com/ObjectDeletionInProgress
```
which eventually become
```
status:
  collisionCount: 0
  conditions:
  - lastTransitionTime: "2021-01-12T20:36:57Z"
    message: Error, timed out while deleting objects
    reason: Timeout
    status: Unknown
    type: ako.vmware.com/ObjectDeletionInProgress
```
