### ISSUE TITLE
enable_rhi Error in ESSENTIALS license

### ISSUE THREAD

**Issue by iXinqi** [vmware/load-balancer-and-ingress-services-for-kubernetes#427]
**Summary:** 
`enable_rhi` can’t be configured with ESSENTIALS license since it is a feature for ENTERPRISE. If omit this field, AKO also throws error that this is a must-have field.

**Detail:**
When LoadBalancer type of service is created in AKO 1.4.1 using essential license, external-ip is pending and the error below shows up:

``` 
2021-04-30T23:03:29.091Z	WARN	rest/dequeue_nodes.go:522	key: admin/tkg-vc-antrea--default-corgi-test, msg: there was an error sending the macro Error during POST: Encountered an error on POST request to URL https://10.186.48.73//api/virtualservice/: HTTP code: 400; error from Avi: map[error:VirtualService.enable_rhi: Field VirtualService.enable_rhi cannot be set in ESSENTIALS license tier.] 
```

If `enable_rhi` is removed from configmap/avi-k8s-config and restart ako, ako pod shows `CreateContainerConfigError`:

```
state:
      waiting:
        message: couldn't find key enableRHI in ConfigMap avi-system/avi-k8s-config
        reason: CreateContainerConfigError
```
