### ISSUE TITLE
AKO Pod Exposes Unnecessary Port - TKGm 1.3.1

### ISSUE THREAD

**Issue by doddatpivotal** [vmware/load-balancer-and-ingress-services-for-kubernetes#473]
Customer is asking why is AKO exposing a port?  There should be no need to access port 80 on the ako pod?  In fact, there is no service object and if you curl the pod ip at port 80 you get a connection refused.  I raised this on slack.  Per Sudipto Biswas.. This is pure noise and an issue should be created.

```
$kubectl get po ako-0 -n avi-system -oyaml
...
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /api/status
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: ako-foo
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    resources:
...
```
